project:
  type: website
  output-dir: docs

website:
  title: "Marshall Washick"
  google-analytics: "G-5XWSFZR6ZS"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Book"
        href: book.qmd
      - text: "Writing"
        href: writing.qmd
      - text: "Consulting"
        href: consulting.qmd
      - text: "Contact"
        href: contact.qmd
    right:
      - icon: linkedin
        href: https://linkedin.com/in/marshallwashick

format:
  html:
    theme: yeti
    css: styles.css
    toc: false



